### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by qnb** [dz0ny/mopidy-youtube#16]
I use this extension with moped (web gui for mopidy) and the YouTube search stopped working around 1-2 weeks ago out of nowhere. I've tried reinstalling the addon and restarting moped but that didn't help.

Someone else is also reporting similar problem here: https://discuss.mopidy.com/t/mopidy-youtube-no-play/585

**Comment by dz0ny** [comment]
Fixed with 4c29fe9161e341948149d5cfd4a1ca055a26a9f4
