### ISSUE TITLE
Fails to play: "Pykka.exceptions.ActorDeadError"

### ISSUE THREAD

**Issue by S0lll0s** [dz0ny/mopidy-youtube#17]
This is the output in the logfiles:

    Mar 15 20:44:11 socke mopidy[1753]: Traceback (most recent call last):
    Mar 15 20:44:11 socke mopidy[1753]: File "/usr/lib/python2.7/site-packages/mopidy/utils/network.py", line 272, in recv_callback
    Mar 15 20:44:11 socke mopidy[1753]: self.actor_ref.tell({'close': True})
    Mar 15 20:44:11 socke mopidy[1753]: File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 437, in tell
    Mar 15 20:44:11 socke mopidy[1753]: raise _ActorDeadError('%s not found' % self)
    Mar 15 20:44:11 socke mopidy[1753]: pykka.exceptions.ActorDeadError: MpdSession (urn:uuid:08d61458-24fb-4b96-87f6-bc8f8ac83693) not found

Adding a youtube playlist worked, but none of the songs would play.

The same happens when I add a single song.

**Comment by jodal** [comment]
This error is from the network connection code trying to stop the `MpdSession` actor because the connection has ended, only to find it is already dead. What would be interesting here is to see why it is already dead. I suspect that is to be found earlier in the same log.

The current log excerpt gives us nothing to work on, unless the issue can be easily reproduced by adding any YouTube playlist to the tracklist.

**Comment by S0lll0s** [comment]
It happens for every youtube video I try to play, and the default-loglevel logs show nothing else.

**Comment by dz0ny** [comment]
Can you confirm that your system can play youtube streams, by issuing following command:

```gst-launch-0.10 playbin2 uri=$(echo "https://www.youtube.com/watch?v=RuY4MSh1V-I" | python2 -c 'import pafy,sys;print(pafy.new("".join(sys.stdin)).getbestaudio().url)')```

**Comment by S0lll0s** [comment]
Will report back when I get home. It seems to be a python error though, it's thrown in `if not data:`.

**Comment by S0lll0s** [comment]
Sorry, I totally forgot about this. Heres the output from running your code (albeit with a different song, yours can't be played in germany):

    gst-launch-0.10 playbin2 uri=(echo "https://www.youtube.com/watch?v=xc96GfmtBB0" | python2 -c 'import pafy,sys;print(pafy.new("".join(sys.stdin)).getbestaudio().url)') 
    Setting pipeline to PAUSED ...
    Pipeline is PREROLLING ...
    Missing element: MPEG-4 AAC decoder
    WARNING: from element /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin0: No decoder available for type 'audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2'.
    Additional debug info:
    gsturidecodebin.c(879): unknown_type_cb (): /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin0
    ERROR: from element /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin0/GstDecodeBin2:decodebin20: Your GStreamer installation is missing a plug-in.
    Additional debug info:
    gstdecodebin2.c(3679): gst_decode_bin_expose (): /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin0/GstDecodeBin2:decodebin20:
    no suitable plugins found
    ERROR: pipeline doesn't want to preroll.
    Setting pipeline to NULL ...
    Freeing pipeline ...

**Comment by S0lll0s** [comment]
Okay, I installed `gstreamer0.1-bad-plugins` - playback works now. Thanks!
